### ISSUE TITLE
How does Unet take a dictionary of emebddings?

### ISSUE THREAD

**Issue by Ruxie189** [jmhb0/view_neti#5]
Hi, 
I have been going through the codes to understand what are the input to the Unet. In my understanding it takes a dictionary of text embeddings, what i am confused about is that how diffusers Unet is able to process a dictionary. I have been normally trying to send a dictionary through Unet but it throws an error. However this code runs perfectly fine. Did you make any specific changes?

Thanks!

**Comment by jmhb0** [comment]
Yeah, in `training/coach.py`, the function `get_text_conditioning` makes a dict of text embeddings. That's because each Unet layer should get a different text embedding.

In coach.py [here](https://github.com/jmhb0/view_neti/blob/6d6605989d527e25156ebb087d21a352418125dc/training/coach.py#L680C1-L681C1), we change how the unet reads the text conditioning in cross-attention layers:
```
self.unet.set_attn_processor(XTIAttenProc())
```
So you might be missing that line. 

The new processor, `XTIAttenProc`, is defined in `models/xti_attention_processor.py`.  You can see in, `__call__()` how it reads the dictionary. 

BTW, this part of the code I inherited from [NETI](https://github.com/NeuralTextualInversion/NeTI), and they took / adapted the XTI attention processor from [promptplusplus](https://github.com/cloneofsimo/promptplusplus). This attn processor is not part of diffusers official library, so it’s possible it might break as that library changes.

**Comment by Ruxie189** [comment]
Thanks! that what i was thinking too :)
